- name: "HolaMundo en Ansible"
  become: true
  hosts: ApacheServer
  tasks:

    - name: "Create a file"
      shell:  "cat \"Hola Mundo DevOps\" >> Ansible_Jenkins_File.dat"
      register: "output"
