- name: "create war file"
  hosts:  local
  become: true
  vars:
          code_dir: "/home/ec2-user/git/DevOpsCodeDemo2"
  tasks:
          - name: "install maven"
            yum:
                  name: maven
          - name: "Copying the code"
            git:
                  repo: 'https://github.com/avaquer8/DevOpsCodeDemo2.git'
                  dest: "{{ code_dir }}"
                  version:  "main"
                  accept_hostkey: yes
                  force: yes
          - name: "Compiling and Packaging"
            command:
                    chdir: "{{ code_dir }}"
                    cmd:  "mvn package"
