- name: "create war file"
  hosts:  AnsibleServer
  become: true
  vars:
          code_dir: "/home/ec2-user/git/DevOpsCodeDemo2"
  tasks:
          - name: "install maven"
            yum:
                  name: maven
