- name: "Install Tomcat and deploy WAR"
  hosts: TomcatAngel
  become: true
  vars:
          gitdir: "/tmp/ProjectDevOpsAngel"
  tasks:
          - name: "Create a file"
            shell:  "uname -an >> /var/lib/tomcat9/webapps/Ansible_Jenkins_File.dat"
            register: "output"
          - name: "Install Tomcat"
            apt:
                    name: tomcat9
                    update_cache: yes
            notify: "enable tomcat service"
          - name: "deploy WAR file"
            copy:
                    src: "{{ gitdir }}/target/BookzyBookShop.war"
                    dest: "/var/lib/tomcat9/webapps/BookzyBookShop.war"            
  handlers:
          - name: "enable tomcat service"
            service:
                    name: tomcat9
                    state: started
                    enabled: yes
          - name: "restart tomcat service post deployment"
            service:
                    name: tomcat9
                    state: restarted            
